name: fracspy
channels:
  - pytorch
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy<2.0.0
  - scipy
  - pandas
  - numba
  - icc_rt
  - matplotlib
  - pylops
  - pytorch
  - tqdm
  - scikit-learn
  - scikit-fmm
  - obspy