name: pyfrac
channels:
  - pytorch
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - numba
  - icc_rt
  - matplotlib
  - pylops
  - ipython
  - jupyter
  - pytorch
  - tqdm
  - scikit-learn
  - scikit-fmm
  - obspy
  - sphinx
  - pydata-sphinx-theme
  - sphinx-gallery
  - numpydoc
  - nbsphinx
  - pip:
    - setuptools_scm