name: pyfrac
channels:
  - pytorch
  - conda-forge
  - numba
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - numba
  - icc_rt
  - matplotlib
  - ipython
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - scikit-learn
  - scikit-fmm
  - sphinx
  - pydata-sphinx-theme
  - sphinx-gallery
  - numpydoc
  - nbsphinx
  - obspy
  - pip:
    - torchsummary
    - openpyxl
    - segyio
    - bm3d    
    - setuptools_scm
    - git+https://github.com/pylops/pylops@dev
    - git+https://github.com/pylops/pyproximal@dev
