name: fracspy
channels:
  - pytorch
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy<2.0.0
  - scipy
  - pandas
  - numba
  - icc_rt
  - matplotlib
  - pylops
  - ipython
  - pytest
  - jupyter
  - pytorch
  - tqdm
  - scikit-learn
  - scikit-fmm
  - obspy
  - cmcrameri
  - sphinx
  - pydata-sphinx-theme
  - sphinx-gallery
  - numpydoc
  - nbsphinx  
  - svgwrite
  - pillow
  - pip:
    - setuptools_scm
    - cairosvg
    