name: Build and test FraCSPy

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, ]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and pyfrac
      run: |
        make dev-install
    - name: Run tests
      run: |
          make tests